pull_request_rules:
  - name: Automatically merge GreenKeeper PRs if tests pass
    conditions:
      - author=greenkeeper
      - status-success="ci/circleci: build"      
    actions:
      merge:
        method: merge